apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.ports.client }}
      name: client
    - port: {{ .Values.service.ports.peer }}
      name: peer
  selector:
    app: {{ .Chart.Name }}
